project_id = "rnzczybbwzkyepwtkfql"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[storage]
file_size_limit = "50MB"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
enable_signup = true

[auth.email]
double_confirm_changes = true
enable_confirmations = false

[functions]

[functions.fetch-ideas]
verify_jwt = false
