// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnzczybbwzkyepwtkfql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuemN6eWJid3preWVwd3RrZnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMjAwMDQsImV4cCI6MjA2Njg5NjAwNH0.r1c97Cd5sdzc7bMPh2c0eMVtqXaSNLRwOCn3r2AcCOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});